server:
  port: 8083
#配置应用名称
spring:
  application:
    name: order
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
      url: jdbc:mysql://192.168.1.34:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false
      username: root
      password: mysql#JN99@dev
      # 使用Druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      druid:
        filters: stat
        maxActive: 10
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        #druid recycle
        remove-abandoned: true
        remove-abandoned-timeout-millis: 300
        log-abandoned: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
#      eureka控制台status后自定义的网址地址，不配置将显示本机ip:client，这个配置的为自定义连接
  instance:
    hostname: 127.0.0.1

#自定义负载均衡
#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
